#!/bin/bash

CURDIRNAME="$(basename "$PWD")"

faile() {
	echo -e "\033[31;1m$*\033[0m"
	exit 1
}

rundocker() {
	( set -x
	docker run --mount="type=bind,source=$PWD,destination=/var/hostdata/$CURDIRNAME" "$@"
	)
}

cenv:rundocker() {
	rundocker -it "$@"
}

cenvb:rundocker() {
    if which busybox >/dev/null ; then
        cenv:rundocker -v "$(which busybox):/bin/busybox" --entrypoint=/bin/busybox "$@" sh
    fi
}

cenvx:rundocker() {
	rundocker -d --net host -e DISPLAY=unix$DISPLAY --device /dev/snd "$@"
}

case "$(basename "$0")" in
	cenv)
		cenv:rundocker "$@" ;;
	cenvx)
		cenvx:rundocker "$@" ;;
	cenvb)
		cenvb:rundocker "$@" ;;
	*)
		faile "Unconfigured comand [$0]" ;;
esac

